name: Auto-Changelog & Julia Register

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Project.toml

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: alex180500/JuliaRegisterChangelog@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}